### ISSUE TITLE
Google maps

### ISSUE THREAD

**Issue by Travis80** [UTSA-CS-3443/Kedro#3]
Figure out how to get google maps on to either an image or whatever it is on an fxml document so that we can use it. Also how to get the location as in the street number and zipcode and country. You can send me messages on here

**Comment by willianet97** [comment]
working on it, way more complicated than what I thought, will have it figured out by monday.

**Comment by Travis80** [comment]
http://java-buddy.blogspot.com/2013/02/embed-google-maps-api-v3-in-javafx.html

You can try this too for google maps
