### ISSUE TITLE
General thread for communications

### ISSUE THREAD

**Issue by Travis80** [UTSA-CS-3443/Kedro#4]
We can use this like slack and add files to it too. Just remember its still public to everyone

**Comment by Travis80** [comment]
First comment

**Comment by Astlky** [comment]
Last comment

**Comment by Astlky** [comment]
That was a test.

**Comment by Travis80** [comment]
I fixed the project thing so if you import it then it only has one project file. So we all good now. Also my phone is dead and I'm at UTSA so if you guys need anything just ask it on here

**Comment by Travis80** [comment]
The master branch doesn't clone correctly so clone the test branch only. It'll ask you which branches right before and make sure you unclick master or it'll bog down

**Comment by brusnak89** [comment]
kyle i sent a text but i know ur phone doesnt work well so hopefully you get this email i need you to add a button to that says search to profile and event i also need a 2 pages with blank hyperlinks 1 for profile and 1 for event to display the results and i also need a view event page with blank labels to display the event information if you could do this asap i would really appreciate it and i hope you get this

**Comment by Astlky** [comment]
Done. Let me know if there's anything else you need.

**Comment by brusnak89** [comment]
its finished
